#!/bin/bash

# SMS to WhatsApp Forwarder - Quick Setup Script
# This script helps you set up the webhook server quickly

set -e

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║    SMS to WhatsApp Forwarder - Quick Setup                ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Check if we're in the examples directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the examples directory"
    echo "   cd examples && ./quick-setup.sh"
    exit 1
fi

echo "🔍 Checking prerequisites..."

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed"
    echo "   Please install Node.js from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node -v)
echo "✅ Node.js $NODE_VERSION installed"

# Check for npm
if ! command -v npm &> /dev/null; then
    echo "❌ npm is not installed"
    exit 1
fi

NPM_VERSION=$(npm -v)
echo "✅ npm $NPM_VERSION installed"

echo ""
echo "📦 Installing dependencies..."
npm install

if [ $? -ne 0 ]; then
    echo "❌ Failed to install dependencies"
    exit 1
fi

echo "✅ Dependencies installed successfully"

# Setup .env file
echo ""
echo "⚙️  Setting up configuration..."

if [ -f ".env" ]; then
    echo "⚠️  .env file already exists. Backing up to .env.backup"
    cp .env .env.backup
fi

# Interactive configuration
echo ""
echo "Please provide the following information:"
echo ""

read -p "WhatsApp target number (with country code, e.g., 1234567890): " WHATSAPP_NUMBER
read -p "Server port (default: 3000): " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-3000}

# Generate random API key
API_KEY=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)

echo ""
echo "Creating .env file..."

cat > .env << EOF
# SMS to WhatsApp Forwarder Configuration
# Generated by quick-setup.sh on $(date)

# Server Configuration
PORT=$SERVER_PORT

# WhatsApp Target Number (with country code, no + symbol)
WHATSAPP_TARGET=$WHATSAPP_NUMBER

# API Key for webhook authentication
API_KEY=$API_KEY

# Twilio Configuration (optional - for twilio-whatsapp-bridge.js)
TWILIO_AUTH_TOKEN=your_twilio_auth_token_here
EOF

echo "✅ Configuration file created"

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║              Setup Complete!                              ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Configuration Summary:"
echo "   • Port: $SERVER_PORT"
echo "   • Target: +$WHATSAPP_NUMBER"
echo "   • API Key: $API_KEY"
echo ""
echo "🚀 To start the webhook server, run:"
echo "   npm start"
echo ""
echo "🔗 Your webhook URL will be:"
echo "   http://your-server-ip:$SERVER_PORT/webhook"
echo ""
echo "🧪 To test the server, run:"
echo "   curl -X POST http://localhost:$SERVER_PORT/test \\"
echo "     -H \"X-API-Key: $API_KEY\""
echo ""
echo "📖 For more information, see:"
echo "   • README.md in this directory"
echo "   • SMS_FORWARDING_GUIDE.md in the parent directory"
echo ""
echo "⚠️  Security Notes:"
echo "   1. Keep your API key secret"
echo "   2. Use HTTPS in production"
echo "   3. Configure firewall rules"
echo "   4. Review the security section in the guide"
echo ""
